#!/usr/bin/env bash
# kernels/build.sh — Assembles a multi-stage Dockerfile from per-language
# profile fragments and builds a bootable bzImage via Docker + kernel-builder.
#
# Usage:
#   kernels/build.sh --lang node@22 --lang python@3.12 --output /path/to/bzImage
#
# Options:
#   --lang  <lang@version>   Language toolchain to include (repeatable)
#   --output <path>          Destination path for the resulting bzImage

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROFILES_DIR="${SCRIPT_DIR}/profiles"

# ── Argument parsing ────────────────────────────────────────────────────────

LANGS=()
OUTPUT=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --lang)
            if [[ -z "${2:-}" ]]; then
                echo "ERROR: --lang requires an argument" >&2
                exit 1
            fi
            LANGS+=("$2")
            shift 2
            ;;
        --output)
            if [[ -z "${2:-}" ]]; then
                echo "ERROR: --output requires an argument" >&2
                exit 1
            fi
            OUTPUT="$2"
            shift 2
            ;;
        *)
            echo "ERROR: Unknown argument: $1" >&2
            exit 1
            ;;
    esac
done

if [[ ${#LANGS[@]} -eq 0 ]]; then
    echo "ERROR: At least one --lang <lang@version> argument is required" >&2
    exit 1
fi

if [[ -z "${OUTPUT}" ]]; then
    echo "ERROR: --output <path> is required" >&2
    exit 1
fi

# ── Dockerfile assembly ─────────────────────────────────────────────────────

TMPDIR="$(mktemp -d)"
DOCKERFILE="${TMPDIR}/Dockerfile"
CONTEXT_DIR="${TMPDIR}/context"
mkdir -p "${CONTEXT_DIR}"

trap 'rm -rf "${TMPDIR}"' EXIT

# Write the base stage header.
cat > "${DOCKERFILE}" <<'HEADER'
# Auto-generated by kernels/build.sh — do not edit by hand.
# syntax=docker/dockerfile:1

# ── Stage 0: base Linux image ───────────────────────────────────────────────
FROM debian:bookworm-slim AS base
RUN apt-get update && apt-get install -y --no-install-recommends \
        openssh-server \
        bash \
        git \
        inotify-tools \
        ca-certificates \
        curl \
        wget \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir -p /run/sshd

HEADER

# Append each per-language fragment.
STAGE_INDEX=1
FINAL_STAGES=()

for LANG_VER in "${LANGS[@]}"; do
    LANG="${LANG_VER%%@*}"
    VERSION="${LANG_VER##*@}"

    FRAGMENT="${PROFILES_DIR}/${LANG}.dockerfile"
    if [[ ! -f "${FRAGMENT}" ]]; then
        echo "ERROR: No profile fragment found for language '${LANG}' at ${FRAGMENT}" >&2
        exit 1
    fi

    STAGE_NAME="lang_${LANG}_${VERSION//\./_}"
    FINAL_STAGES+=("${STAGE_NAME}")

    {
        echo ""
        echo "# ── Stage ${STAGE_INDEX}: ${LANG} @ ${VERSION} ──────────────────────────────────────────"
        echo "FROM base AS ${STAGE_NAME}"
        echo "ARG LANG_VERSION=${VERSION}"
        # Inject the VERSION variable so the fragment can reference \$LANG_VERSION.
        echo "ENV LANG_VERSION=${VERSION}"
        cat "${FRAGMENT}"
        echo ""
    } >> "${DOCKERFILE}"

    STAGE_INDEX=$((STAGE_INDEX + 1))
done

# Write the final merged stage that copies toolchains from each lang stage.
cat >> "${DOCKERFILE}" <<'FINAL_HEADER'
# ── Final stage: merged image ────────────────────────────────────────────────
FROM base AS final
FINAL_HEADER

for STAGE in "${FINAL_STAGES[@]}"; do
    echo "COPY --from=${STAGE} /usr/local/ /usr/local/" >> "${DOCKERFILE}"
    echo "COPY --from=${STAGE} /opt/ /opt/" >> "${DOCKERFILE}"
done

cat >> "${DOCKERFILE}" <<'FINAL_FOOTER'

# Expose SSH.
EXPOSE 22

# Default: start sshd in the foreground.
CMD ["/usr/sbin/sshd", "-D"]
FINAL_FOOTER

echo "INFO: Assembled Dockerfile at ${DOCKERFILE}"
if [[ "${CLAUDEBOX_DEBUG:-}" == "1" ]]; then
    echo "──────────────── Dockerfile ────────────────"
    cat "${DOCKERFILE}"
    echo "────────────────────────────────────────────"
fi

# ── Docker build + kernel extraction ────────────────────────────────────────

IMAGE_TAG="claudebox-kernel-$(date +%s)"

echo "INFO: Building Docker image '${IMAGE_TAG}' …"
docker buildx build \
    --file "${DOCKERFILE}" \
    --tag "${IMAGE_TAG}" \
    --load \
    "${CONTEXT_DIR}"

echo "INFO: Extracting bzImage from image '${IMAGE_TAG}' …"

# The kernel is expected at /boot/bzImage inside the image produced by the
# kernel-builder toolchain (linuxkit or a custom buildroot image).  Adjust
# the path here if your build process places it elsewhere.
CONTAINER_ID="$(docker create "${IMAGE_TAG}")"
trap 'docker rm -f "${CONTAINER_ID}" 2>/dev/null || true; rm -rf "${TMPDIR}"' EXIT

OUTPUT_DIR="$(dirname "${OUTPUT}")"
mkdir -p "${OUTPUT_DIR}"

docker cp "${CONTAINER_ID}:/boot/bzImage" "${OUTPUT}"

echo "INFO: bzImage written to ${OUTPUT}"
